### ISSUE TITLE
Problems with prometheus.Handler()

### ISSUE THREAD

**Issue by MrLouzao** [ejhsu/go-prometheus-exporter#1]
Hi ejhsu!

I've found an issue with this project when trying the medium tutorial. The issue is related to prometheus dependency. Check the **line 34** on **server.go** when calling prometheus.Handler(). It seems like this method is deprecated.

Use instead:
`
http.Handle(metricsSuffix, promhttp.Handler())
`

Also you must import the dependency:
`
"github.com/prometheus/client_golang/prometheus/promhttp"
`

Then it works like a charm :)
Regards!

**Comment by ejhsu** [comment]
Hi @MrLouzao,

It should not be a problem if you installed prometheus dependency by the version defined in `Gopkg.lock` (using dep ensure).
But sure, I've updated server.go and use `promhttp.Handler()` instead.

Thanks for your feedback! 😄 
Regards.
